allowBuilds:
  '@swc/core': false
  esbuild: false
  tree-sitter-c: set this to true or false
  tree-sitter-cpp: set this to true or false
  tree-sitter-go: set this to true or false
  tree-sitter-java: set this to true or false
  tree-sitter-javascript: false
  tree-sitter-kotlin: false
  tree-sitter-python: false
  tree-sitter-rust: set this to true or false
  tree-sitter-typescript: false
